name: coverage
on:
  push:
    branches:
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send Coverage Report To Codacy
        run: |
          npm ci
          npm run coverage
          CODACY_PROJECT_TOKEN=${{ secrets.CODACY_SECRET }} bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info